In [14]:
import pandas as pd
from pathlib import Path

# Ajuste ce chemin si besoin pour pointer sur ton dossier « curated »
CURATED = Path("../data/curated")

expected_feats = [
    'efg_pct','ts_pct','stl_mean','blk_mean','tov_mean',
    'pts36','reb36','ast36','stl36','blk36','tov36','pm36'
]

records = []
for path in sorted(CURATED.glob("player_season_*.parquet")):
    season = path.stem.split("_")[-1]
    cols = pd.read_parquet(path).columns.tolist()
    missing = [f for f in expected_feats if f not in cols]
    records.append({"season": season, "missing_features": missing})

df_check = pd.DataFrame(records)

# 1) soit :
df_check

# 2) ou, si tu préfères, :
# from IPython.display import display
# display(df_check)

     season missing_features
0   1999-00               []
1   2000-01               []
2   2001-02               []
3   2002-03               []
4   2003-04               []
5   2004-05               []
6   2005-06               []
7   2006-07               []
8   2007-08               []
9   2008-09               []
10  2009-10               []
11  2010-11               []
12  2011-12               []
13  2012-13               []
14  2013-14               []
15  2014-15               []
16  2015-16               []
17  2016-17               []
18  2017-18               []
19  2018-19               []
20  2019-20               []
21  2020-21               []
22  2021-22               []
23  2022-23               []
24  2023-24               []